version: '3.1'
services:

  render:
    build: ./
    image: home.4it.me:5000/ofc-render:latest
    command: node .
    volumes:
      - nfsUploads:/app/uploads
    environment:
      ADMIN_AUTH_TOKEN: ${ADMIN_AUTH_TOKEN}
      STL_DIR: /app/uploads

volumes:
  nfsUploads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=api.online.fdm.center
      device: ":/home/dilap54/server/uploads"
